import type { Metadata } from "next";
import { Geist } from "next/font/google";

import "../styles/globals.css";

import type { ReactNode } from "react";

import { ProviderTree } from "@/providers";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html
      className={`${geist.variable} antialiased`}
      lang="en"
      suppressHydrationWarning={true}
    >
      <body className="flex flex-col min-h-screen">
        <ProviderTree>{children}</ProviderTree>
      </body>
    </html>
  );
};

export default RootLayout;
